appName: simpleserver
namespace: simpleserver


image:
  repository: juanjcsr/simpleserver
  tag: 6f26f57274a0f1782083a10ea8cdfb605f4e85b2

replicas: 4

service:
  enabled: true
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP
