appName: simpleserver
namespace: simpleserver


image:
  repository: juanjcsr/simpleserver
  tag: 5c3f3b414b5fb1edc617ef070685b433c5d96d7c

replicas: 10

service:
  enabled: true
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP
