appName: simpleserver
namespace: simpleserver


image:
  repository: juanjcsr/simpleserver
  tag: db86b02fb2e9ed2e0cef08f27da2340f66a8b7f4

replicas: 3

service:
  enabled: true
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP
