appName: simpleserver
namespace: simpleserver


image:
  repository: juanjcsr/simpleserver
  tag: b4928cd535ca29d3dff0fa4c47d38aa7ec9e30ce

replicas: 2

service:
  enabled: true
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP
