appName: simpleserver
namespace: simpleserver


image:
  repository: juanjcsr/simpleserver
  tag: 61a83bf817b1506f5be150e5c43d5b938fe7e897

replicas: 1

service:
  enabled: true
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP
