appName: simpleserver
namespace: simpleserver


image:
  repository: juanjcsr/simpleserver
  tag: 4e96a3dccb2a49c2263baefa7462cee76334d1b7

replicas: 5

service:
  enabled: true
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP
