appName: simpleserver
namespace: simpleserver


image:
  repository: juanjcsr/simpleserver
  tag: 3b3f10d20bcef5953d1767e4cc94eece19718433


limits:
  cpu: 100m
  memory: 128Mi

requests:
  cpu: 100m
  memory: 128Mi

replicas: 4

service:
  enabled: true
  type: NodePort
  port: 8080
  targetPort: 8080
  protocol: TCP
