---
# Source: defaultapptemplate/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: simpleserver-service
  namespace: simpleserver
spec:
  selector:
    app: simpleserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: defaultapptemplate/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleserver-app
  labels:
    app: simpleserver
  annotations:
    linkerd.io/inject: enabled
spec:
  replicas: 4
  selector:
    matchLabels:
      app: simpleserver
  template:
    metadata:
      labels:
        app: simpleserver
    spec:
      containers:
        - name: simpleserver
          image: "juanjcsr/simpleserver:f4b79a91e507c3ac791740ffbdabddfc35c85c27"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
# Source: defaultapptemplate/templates/hpa.yaml
# This is the Horizontal Pod Autoscaler (HPA) configuration file.
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: simpleserver-hpa
  namespace: simpleserver
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simpleserver-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target: 
          type: Utilization
          averageUtilization: 50
