---
# Source: defaultapptemplate/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: simpleserver
---
# Source: defaultapptemplate/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: simpleserver-service
  namespace: simpleserver
spec:
  selector:
    app: simpleserver
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: defaultapptemplate/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleserver-app
  labels:
    app: simpleserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simpleserver
  template:
    metadata:
      labels:
        app: simpleserver
    spec:
      containers:
        - name: simpleserver
          image: "juanjcsr/simpleserver:61a83bf817b1506f5be150e5c43d5b938fe7e897"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
