---
# Source: defaultapptemplate/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: simpleserver
---
# Source: defaultapptemplate/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleserver-app
  labels:
    app: simpleserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleserver
  template:
    metadata:
      labels:
        app: simpleserver
    spec:
      containers:
        - name: simpleserver
          image: "juanjcsr/simpleserver:80d7b31cffa8bf7ba9fc261bd4a3be101d9a1dcf"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
