---
# Source: defaultapptemplate/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: simpleserver-service
  namespace: simpleserver
spec:
  selector:
    app: simpleserver
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: defaultapptemplate/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleserver-app
  labels:
    app: simpleserver
spec:
  replicas: 4
  selector:
    matchLabels:
      app: simpleserver
  template:
    metadata:
      labels:
        app: simpleserver
    spec:
      containers:
        - name: simpleserver
          image: "juanjcsr/simpleserver:3b3f10d20bcef5953d1767e4cc94eece19718433"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
