{{- if .Values.hpa.enabled }}
---
# This is the Horizontal Pod Autoscaler (HPA) configuration file.
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-app
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    {{- if .Values.hpa.metrics.cpu.enabled }}
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: {{ .Values.hpa.metrics.cpu.targetAverageUtilization }}
    {{- end }}
    {{- if .Values.hpa.metrics.memory.enabled }}
    - type: Resource
      resource:
        name: memory
        target: 
          type: Utilization
          averageUtilization: {{ .Values.hpa.metrics.memory.targetAverageUtilization }}
    {{- end }}
{{- end }}
