argo-cd:
  syncPolicy:
    automated:
      prune: true
  dex:
    enabled: false
  deploymentAnnotations:
    linkerd.io/inject: enabled
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
