apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.appName }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/juanjcsr/terraploy.git
    path: "charts/{{ .Values.appName }}"
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: {{default "default" .Values.namespace }}
  syncPolicy:
    automated:
      selfHeal: true
