name: build docker image
on: [push]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKER_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    
    - name: get diff from definition file
      id: get_diff
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} > diff.txt
        echo "image_to_build=$(cat diff.txt | grep '^apps/' | awk -F/ '{print $2}' | sort | uniq)" >> $GITHUB_OUTPUT
        
    - name: Build Docker Image
      run: |
        IMAGE_TO_BUILD=$(cat diff.txt | grep '^apps/' | awk -F/ '{print $2}' | sort | uniq)
        echo "image_to_build=$(echo $IMAGE_TO_BUILD)" >> $GITHUB_ENV

        docker build -t ${{ env.DOCKERHUB_USERNAME }}/$IMAGE_TO_BUILD:$GITHUB_SHA -f apps/$IMAGE_TO_BUILD/Dockerfile apps/$IMAGE_TO_BUILD
      if: |
        env.image_to_build != ''
    - name: Push Docker Image
      run: |
        IMAGE_TO_BUILD=$(cat diff.txt | grep '^apps/' | awk -F/ '{print $2}' | sort | uniq)
        echo $IMAGE_TO_BUILD

        docker push ${{ env.DOCKERHUB_USERNAME }}/$IMAGE_TO_BUILD:$GITHUB_SHA
      if: |
        github.event_name != 'pull_request' &&
        env.image_to_build != ''

    - name: create argo application
      run: |
        if [ ${{env.image_to_build}} -neq '' ] && [ test -f "charts/{{env.image_to_build}}" ]; then
          echo "file exists"
        fi

      
    
