name: build docker image
on: [push]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKER_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    
    - name: get diff from definition file
      id: get_diff
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} > diff.txt
        echo "IMAGE_TO_BUILD={$(cat diff.txt | awk -F/ '{print $2}' | sort | uniq)}"
    - name: Build and push
      run: |
        IMAGE_TO_BUILD=$(cat diff.txt | awk -F/ '{print $2}' | sort | uniq)
        echo $IMAGE_TO_BUILD
