on:
  workflow_call:
    outputs:
      app_to_deploy:
        description: 'app to deploy'
        value: ${{ jobs.get-diff.outputs.image_to_build }}


jobs:
  get_diff:
    runs-on: ubuntu-latest
    outputs:
      image_to_build: ${{ steps.get-diff.outputs.image_to_build }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: get changed files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          apps/**
          definition/**
        write_output_files: true
    - name: Verify the contents of the .github/outputs/all_changed_and_modified_files file
      id: get-diff
      run: |
        cat .github/outputs/all_changed_and_modified_files.txt
        image_to_build=$(cat .github/outputs/all_changed_and_modified_files.txt | grep -Eo '(apps|definition)/[^/]+' | awk -F/ '{print $2}' | sort | uniq)
        echo "image_to_build=$image_to_build" >> $GITHUB_OUTPUT
        echo $image_to_build
       
    